'ANALISTA (NQ)' , 'ANALISTA DE ORDENAMENTO TERRITORIAL (NQ)NIVEL I' , 'ANALISTA DE ORDENAMENTO TERRITORIAL (NQ)NIVEL IV' , 'ANALISTA FISCAL DE SERVICOS (NQ)NIVEL I' ,
'ANALISTA PLANEJAMENTO DESENV ORGANIZACIONAL (NQ)NIVEL III' , 'ANALISTA PLANEJAMENTO DESENV ORGANIZACIONAL (NQ)NIVEL IV' , 'ASSESSOR I' , 'ASSESSOR II' , 'ASSESSOR III' ,
'ASSESSOR IV' , 'ASSESSOR V' , 'ASSESSOR VI' , 'ASSISTENTE ADMINISTRATIVO DE GESTAO' , 'ASSISTENTE ADMINISTRATIVO DE GESTAO NIVEL I' , 'ASSISTENTE ADMINISTRATIVO DE GESTAO NIVEL II' ,
'ASSISTENTE DE GESTAO DE POLITICAS PUBLICAS NIVEL II' , 'ASSISTENTE DE SUPORTE OPERACIONAL NIVEL I' , 'ASSISTENTE DE SUPORTE OPERACIONAL NIVEL II' , 'CHEFE DE ASSESSORIA II' , 'CHEFE DE GABINETE' ,
'COORDENADOR I' , 'DIRETOR I' , 'DIRETOR II' , 'ESP DESENVOLVIMENTO URBANO NÍVEL II' , 'FISCAL DE POSTURAS MUNICIPAIS NIVEL I' , 'FISCAL DE POSTURAS MUNICIPAIS NIVEL II' ,
'FISCAL DE POSTURAS MUNICIPAIS NIVEL III' , 'PROCURADOR DO MUNICIPIO I' , 'PROCURADOR DO MUNICIPIO II' , 'PROCURADOR DO MUNICIPIO III' , 'PROFISSIONAL ENG, ARQ, AGRONOMIA,GEOLOGIA NIVEL I' ,
'PROFISSIONAL ENG, ARQ, AGRONOMIA,GEOLOGIA NIVEL II' , 'PROFISSIONAL ENG, ARQ, AGRONOMIA,GEOLOGIA NIVEL IV' , 'SECRETARIO EXECUTIVO' , 'SECRETARIO EXECUTIVO ADJUNTO' , 'SECRETARIO MUNICIPAL' ,
'SECRETARIO-ADJUNTO'
